// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using ServerService.Domain;

#nullable disable

namespace ServerService.Migrations
{
    [DbContext(typeof(TreeContext))]
    [Migration("20240120122917_initialmig")]
    partial class initialmig
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "ltree");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ServerService.Models.Tree", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("uuid");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Sorting")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("character varying(5)");

                    b.HasKey("Id");

                    b.ToTable("Trees");
                });

            modelBuilder.Entity("ServerService.Models.TreeItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("EntityId")
                        .HasColumnType("uuid");

                    b.Property<string>("EntityValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("MaterializedPath")
                        .IsRequired()
                        .HasColumnType("ltree");

                    b.Property<Guid?>("ParentEntityId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TreeKey")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("EntityId");

                    b.HasIndex("MaterializedPath");

                    NpgsqlIndexBuilderExtensions.HasMethod(b.HasIndex("MaterializedPath"), "gist");

                    b.HasIndex("ParentEntityId");

                    b.HasIndex("TreeKey");

                    b.ToTable("TreeItems");
                });
#pragma warning restore 612, 618
        }
    }
}
